### PR TITLE
the binary view already exists

### LINKED ISSUE #55: minor doc
Just wanted to implement the binary view, only to find it already is since bc757ec6107052c2c6ba8a744aa0387bacc9332d.
@prohde may you overlook that todo-list?

### PR DESCRIPTION
**Pull request by AiyionPrime**
This was handled in 2017.
closes #55

### CODE REVIEW

**Review by prohde — APPROVED** [review]

**Review by prohde — APPROVED** [review]

**Comment by prohde** [comment]
@dkiechle Any news on this PR?

**Comment by AiyionPrime** [comment]
Not from my side; I just took part in the course last winter.
I think it would be nice to get some form of feedback from @luhsra; as neither of us two has access to the master branch.

**Comment by AiyionPrime** [comment]
@nnamua If you're interested, I can rebase my remaining branches this evening.

**Comment by AiyionPrime** [comment]
@nnamua Rebased, ready to merge.

**Comment by prohde** [comment]
@nnamua Are there any issues with merging this PR?

**Pull request merged**
